### PR TITLE
Fix browser demo error management

### LINKED ISSUE #3841: Type error: Object literal may only specify known properties, and 'onError' does not exist in type 'IHandleIncomingRedirectOptions'.
I'm getting this error when trying to compile https://github.com/inrupt/solid-client-authn-js/blob/main/packages/browser/examples/single/bundle/src/App.js#L51 as TypeScript.
Is it missing from 'IHandleIncomingRedirectOptions'?

### PR DESCRIPTION
**Pull request by NSeydoux**
Fixes #3841.

The browser demo no longer passes an incorrect argument (from a TS perspective) to the `handleIncomingRedirect` function. This also fixes how the React app root is created with respect to the latest upgrade.

### CODE REVIEW

**Review by chelseapinka — APPROVED** [review]

File: packages/browser/examples/single/bundle/src/App.js [hunk 1]
```diff
@@ -59,10 +60,9 @@ export default function App() {
     console.log(`${error} has occured: `, errorDescription);
   };
 
-  const handleLogin = (e) => {
-    // The default behaviour of the button is to resubmit.
-    // This prevents the page from reloading.
-    e.preventDefault();
+  events().on(EVENTS.ERROR, errorHandle);
```
Comment (NSeydoux) [inline packages/browser/examples/single/bundle/src/App.js:63]: This is how error events should be handled on the session.

File: packages/browser/examples/single/bundle/src/index.js [hunk 2]
```diff
@@ -20,7 +20,7 @@
 //
 
 import React from "react";
-import ReactDOM from "react-dom";
+import { createRoot } from 'react-dom/client';
 import App from "./App";
 
-ReactDOM.render(<App />, document.getElementById("container"));
```
Comment (NSeydoux) [inline packages/browser/examples/single/bundle/src/index.js:26]: This approach was deprecated from React in a previous version.

**Review by chelseapinka — APPROVED** [review]
